###############################################################
#  Generated by:      Cadence Innovus 16.13-s045_1
#  OS:                Linux x86_64(Host ID almansur.fransg.eit.lth.se)
#  Generated on:      Fri May 17 11:16:44 2024
#  Design:            pulpino_top_rtl_w_pads
#  Command:           create_ccopt_clock_tree_spec -file ./ccopt.spec
###############################################################
#-------------------------------------------------------------------------------
# Clock tree setup script - dialect: Innovus
#-------------------------------------------------------------------------------
#-------------------------------------------------------------------------------

namespace eval ::ccopt {}
namespace eval ::ccopt::ilm {}
set ::ccopt::ilm::ccoptSpecRestoreData {}
# Start by checking for unflattened ILMs.
# Will flatten if so and then check the db sync.
if { [catch {ccopt_check_and_flatten_ilms_no_restore}] } {
  return -code error
}
# cache the value of the restore command output by the ILM flattening code
set ::ccopt::ilm::ccoptSpecRestoreData $::ccopt::ilm::ccoptRestoreILMState

# Clocks present at pin spi_clk
#   clk_spi (period 100.000ns) in timing_config Clock_Constraint([/h/d7/z/vi0873st-s/Documents/etin35-pulpino/pnr/pulpino_top_rtl_w_pads_0.dat/libs/mmmc/pulpino_top_rtl_w_pads.sdc])
create_ccopt_clock_tree -name clk_spi -source spi_clk -no_skew_group

set_ccopt_property target_max_trans_sdc -delay_corner SS -late -clock_tree clk_spi 0.200
# Clock tree offset inferred from set_clock_latency -source assertions:
set_ccopt_property source_latency -delay_corner SS -late -rise -clock_tree clk_spi 0.500
set_ccopt_property source_latency -delay_corner SS -late -fall -clock_tree clk_spi 0.500
set_ccopt_property source_latency -delay_corner FF -late -rise -clock_tree clk_spi 0.500
set_ccopt_property source_latency -delay_corner FF -late -fall -clock_tree clk_spi 0.500
# Clock period setting for source pin of clk_spi
set_ccopt_property clock_period -pin spi_clk 100

# Clocks present at pin jtag_clk
#   clk_jtag (period 100.000ns) in timing_config Clock_Constraint([/h/d7/z/vi0873st-s/Documents/etin35-pulpino/pnr/pulpino_top_rtl_w_pads_0.dat/libs/mmmc/pulpino_top_rtl_w_pads.sdc])
create_ccopt_clock_tree -name clk_jtag -source jtag_clk -no_skew_group

set_ccopt_property target_max_trans_sdc -delay_corner SS -late -clock_tree clk_jtag 0.200
# Clock tree offset inferred from set_clock_latency -source assertions:
set_ccopt_property source_latency -delay_corner SS -late -rise -clock_tree clk_jtag 0.500
set_ccopt_property source_latency -delay_corner SS -late -fall -clock_tree clk_jtag 0.500
set_ccopt_property source_latency -delay_corner FF -late -rise -clock_tree clk_jtag 0.500
set_ccopt_property source_latency -delay_corner FF -late -fall -clock_tree clk_jtag 0.500
# Clock period setting for source pin of clk_jtag
set_ccopt_property clock_period -pin jtag_clk 100

# Clocks present at pin clk
#   clk (period 40.000ns) in timing_config Clock_Constraint([/h/d7/z/vi0873st-s/Documents/etin35-pulpino/pnr/pulpino_top_rtl_w_pads_0.dat/libs/mmmc/pulpino_top_rtl_w_pads.sdc])
create_ccopt_clock_tree -name clk -source clk -no_skew_group

set_ccopt_property target_max_trans_sdc -delay_corner SS -late -clock_tree clk 0.200
# Clock tree offset inferred from set_clock_latency -source assertions:
set_ccopt_property source_latency -delay_corner SS -late -rise -clock_tree clk 0.500
set_ccopt_property source_latency -delay_corner SS -late -fall -clock_tree clk 0.500
set_ccopt_property source_latency -delay_corner FF -late -rise -clock_tree clk 0.500
set_ccopt_property source_latency -delay_corner FF -late -fall -clock_tree clk 0.500
# Clock period setting for source pin of clk
set_ccopt_property clock_period -pin clk 40

# Skew group to balance non generated clock:clk in timing_config:Clock_Constraint (sdc /h/d7/z/vi0873st-s/Documents/etin35-pulpino/pnr/pulpino_top_rtl_w_pads_0.dat/libs/mmmc/pulpino_top_rtl_w_pads.sdc)
create_ccopt_skew_group -name clk/Clock_Constraint -sources clk -auto_sinks
set_ccopt_property include_source_latency -skew_group clk/Clock_Constraint true
set_ccopt_property extracted_from_clock_name -skew_group clk/Clock_Constraint clk
set_ccopt_property extracted_from_constraint_mode_name -skew_group clk/Clock_Constraint Clock_Constraint
set_ccopt_property extracted_from_delay_corners -skew_group clk/Clock_Constraint {SS FF}

# Skew group to balance non generated clock:clk_jtag in timing_config:Clock_Constraint (sdc /h/d7/z/vi0873st-s/Documents/etin35-pulpino/pnr/pulpino_top_rtl_w_pads_0.dat/libs/mmmc/pulpino_top_rtl_w_pads.sdc)
create_ccopt_skew_group -name clk_jtag/Clock_Constraint -sources jtag_clk -auto_sinks
set_ccopt_property include_source_latency -skew_group clk_jtag/Clock_Constraint true
set_ccopt_property target_insertion_delay -skew_group clk_jtag/Clock_Constraint 1.000
set_ccopt_property extracted_from_clock_name -skew_group clk_jtag/Clock_Constraint clk_jtag
set_ccopt_property extracted_from_constraint_mode_name -skew_group clk_jtag/Clock_Constraint Clock_Constraint
set_ccopt_property extracted_from_delay_corners -skew_group clk_jtag/Clock_Constraint {SS FF}

# Skew group to balance non generated clock:clk_spi in timing_config:Clock_Constraint (sdc /h/d7/z/vi0873st-s/Documents/etin35-pulpino/pnr/pulpino_top_rtl_w_pads_0.dat/libs/mmmc/pulpino_top_rtl_w_pads.sdc)
create_ccopt_skew_group -name clk_spi/Clock_Constraint -sources spi_clk -auto_sinks
set_ccopt_property include_source_latency -skew_group clk_spi/Clock_Constraint true
set_ccopt_property target_insertion_delay -skew_group clk_spi/Clock_Constraint 1.000
set_ccopt_property extracted_from_clock_name -skew_group clk_spi/Clock_Constraint clk_spi
set_ccopt_property extracted_from_constraint_mode_name -skew_group clk_spi/Clock_Constraint Clock_Constraint
set_ccopt_property extracted_from_delay_corners -skew_group clk_spi/Clock_Constraint {SS FF}


check_ccopt_clock_tree_convergence
# Restore the ILM status if possible
if { [get_ccopt_property auto_design_state_for_ilms] == 0 } {
  if {$::ccopt::ilm::ccoptSpecRestoreData != {} } {
    eval $::ccopt::ilm::ccoptSpecRestoreData
  }
}

